name: example

environment:  
  sdk: ">=2.6.1 <3.0.0"

dependencies:
  create_from_e_annotation:
    path: ../create_from_e_annotation/

dev_dependencies:
  build_runner: ^1.7.3
  test: ^1.11.1
  create_from_e_generator:
    path: ../create_from_e_generator/